database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/task_servlet
  user: postgres
  password: root
  min: 2
  max: 100
  autocommit: true
  timeout: 10000
  auto_init: true
  add_data: true
  schema_sql: WEB-INF/classes/sql/schema.sql
  data_sql: WEB-INF/classes/sql/data.sql
  drop_sql: WEB-INF/classes/sql/drop.sql
cache:
  type: LFU
  size: 10
pdf:
  background_path: pdf/Clevertec_Template.pdf
  output_path: output/result.pdf
  font_path: pdf/arial.ttf
pagination:
  limit: 20