database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/task_servlet
  user: postgres
  password: root
  min: 2
  max: 100
  autocommit: true
  timeout: 10000
  auto_init: true
  add_data: true
  sql:
    schema: sql/schema.sql
    data: sql/data.sql
    drop: sql/drop.sql
cache:
  type: LFU
  size: 10
pdf:
  path:
    background: pdf/Clevertec_Template.pdf
    output: output/result.pdf
    font: pdf/arial.ttf
pagination:
  limit: 20